

development:
  adapter: postgresql
  encoding: unicode
  database: lazycoffee_development
  


test:
  adapter: postgresql
  encoding: unicode
  database: lazycoffee_test


production:
  adapter: postgresql
  encoding: unicode
  database: lazycoffee_production

