
development:
  adapter: postgresql
  encoding: unicode
  database: review-store_development
  
  
test:
  adapter: postgresql
  encoding: unicode
  database: review-store_test
  

production:
  adapter: postgresql
  encoding: unicode
  database: review-store_production
