
development:
  adapter: postgresql
  database: stackoverflow_clone_development


test:
  adapter: postgresql
  database: stackoverflow_clone_test


# production:
#   adapter: postgresql
#   encoding: unicode
#   database: stackoverflow_clone_production
#   pool: 5
#   username: stackoverflow_clone
#   password:
